[versions]
agp = "8.6.0"
kotlin = "1.9.24"
coreKtx = "1.13.1"
appcompat = "1.7.1"
material = "1.13.0"

lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.9.0"
composeBom = "2025.12.01"

retrofit_version = "2.11.0"
okhttp_version = "4.12.0"

junit = "4.13.2"
coroutines_test = "1.8.1"
mockito = "5.12.0"


hilt_version = "2.54"
hiltNavigationCompose = "1.1.0"

javax = "1"

coil = "2.6.0"
uiTestJunit4 = "1.10.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit_version" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit_version" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp_version" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp_version" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt_version" }
hilt-android-compile = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt_version" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines_test" }

javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javax" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "uiTestJunit4" }

[bundles]
networkClient = ["retrofit", "okhttp-logging-interceptor", "okhttp", "retrofit-converter-gson"]
hilt = ["hilt-android", "hilt-android-compile", "androidx-hilt-navigation-compose"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt_version" }
